IF SCHEMA_ID(N'CATALOGOS') IS NULL EXEC(N'CREATE SCHEMA [CATALOGOS]');
IF SCHEMA_ID(N'ADMINISTRACION_USUARIOS') IS NULL EXEC(N'CREATE SCHEMA [ADMINISTRACION_USUARIOS]');
IF SCHEMA_ID(N'INVENTARIO') IS NULL EXEC(N'CREATE SCHEMA [INVENTARIO]');
IF SCHEMA_ID(N'CLIENTES') IS NULL EXEC(N'CREATE SCHEMA [CLIENTES]');
IF SCHEMA_ID(N'CLINICA') IS NULL EXEC(N'CREATE SCHEMA [CLINICA]');
IF SCHEMA_ID(N'COMERCIAL_VENTAS') IS NULL EXEC(N'CREATE SCHEMA [COMERCIAL_VENTAS]');
IF SCHEMA_ID(N'AUDITORIA') IS NULL EXEC(N'CREATE SCHEMA [AUDITORIA]');
IF SCHEMA_ID(N'REPORTES') IS NULL EXEC(N'CREATE SCHEMA [REPORTES]');
IF SCHEMA_ID(N'NOTIFICACIONES') IS NULL EXEC(N'CREATE SCHEMA [NOTIFICACIONES]');

IF OBJECT_ID(N'[CATALOGOS].EstadosOrden', N'U') IS NULL
CREATE TABLE [CATALOGOS].EstadosOrden
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_EstadosOrden PRIMARY KEY,
    CODIGO nvarchar(30) NOT NULL,
    NOMBRE nvarchar(100) NOT NULL,
    ACTIVO bit NOT NULL CONSTRAINT DF_EstadosOrden_ACTIVO DEFAULT(1),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_EstadosOrden_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_EstadosOrden_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT UQ_EstadosOrden_CODIGO UNIQUE(CODIGO)
);

IF OBJECT_ID(N'[CATALOGOS].MetodosPago', N'U') IS NULL
CREATE TABLE [CATALOGOS].MetodosPago
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_MetodosPago PRIMARY KEY,
    CODIGO nvarchar(30) NOT NULL,
    NOMBRE nvarchar(100) NOT NULL,
    ACTIVO bit NOT NULL CONSTRAINT DF_MetodosPago_ACTIVO DEFAULT(1),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_MetodosPago_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_MetodosPago_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT UQ_MetodosPago_CODIGO UNIQUE(CODIGO)
);

IF OBJECT_ID(N'[CATALOGOS].FiltrosLente', N'U') IS NULL
CREATE TABLE [CATALOGOS].FiltrosLente
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_FiltrosLente PRIMARY KEY,
    NOMBRE nvarchar(50) NOT NULL,
    ACTIVO bit NOT NULL CONSTRAINT DF_FiltrosLente_ACTIVO DEFAULT(1),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_FiltrosLente_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_FiltrosLente_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT UQ_FiltrosLente_NOMBRE UNIQUE(NOMBRE)
);

IF OBJECT_ID(N'[CATALOGOS].TiposIDentificacion', N'U') IS NULL
CREATE TABLE [CATALOGOS].TiposIDentificacion
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_TiposIDentificacion PRIMARY KEY,
    NOMBRE nvarchar(100) NOT NULL,
    ACTIVO bit NOT NULL CONSTRAINT DF_TiposIDentificacion_ACTIVO DEFAULT(1),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_TiposIDentificacion_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_TiposIDentificacion_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME())
);

IF OBJECT_ID(N'[ADMINISTRACION_USUARIOS].Empleados', N'U') IS NULL
CREATE TABLE [ADMINISTRACION_USUARIOS].Empleados
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_Empleados PRIMARY KEY,
    NOMBRE nvarchar(100) NOT NULL,
    APELLIDO nvarchar(100) NOT NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_Empleados_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_Empleados_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME())
);

IF OBJECT_ID(N'[ADMINISTRACION_USUARIOS].Roles', N'U') IS NULL
CREATE TABLE [ADMINISTRACION_USUARIOS].Roles
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_Roles PRIMARY KEY,
    CODIGO nvarchar(30) NOT NULL,
    NOMBRE nvarchar(100) NOT NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_Roles_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_Roles_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT UQ_Roles_CODIGO UNIQUE(CODIGO)
);

IF OBJECT_ID(N'[ADMINISTRACION_USUARIOS].Usuarios', N'U') IS NULL
CREATE TABLE [ADMINISTRACION_USUARIOS].Usuarios
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_Usuarios PRIMARY KEY,
    EMPLEADO_ID bigint NOT NULL,
    NOMBRE_USUARIO nvarchar(100) NOT NULL,
    PASSWORD_HASH varbinary(256) NOT NULL,
    PASSWORD_SALT varbinary(128) NOT NULL,
    ACTIVO bit NOT NULL CONSTRAINT DF_Usuarios_ACTIVO DEFAULT(1),
    BLOQUEADO_HASTA datetime2(7) NULL,
    INTENTOS_FALLIDOS int NOT NULL CONSTRAINT DF_Usuarios_INTENTOS_FALLIDOS DEFAULT(0),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_Usuarios_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_Usuarios_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT UQ_Usuarios_Empleado UNIQUE(EMPLEADO_ID),
    CONSTRAINT UQ_Usuarios_NOMBRE_USUARIO UNIQUE(NOMBRE_USUARIO),
    CONSTRAINT FK_Usuarios_Empleados FOREIGN KEY(EMPLEADO_ID) REFERENCES [ADMINISTRACION_USUARIOS].Empleados(ID)
);

IF OBJECT_ID(N'[ADMINISTRACION_USUARIOS].UsuariosRoles', N'U') IS NULL
CREATE TABLE [ADMINISTRACION_USUARIOS].UsuariosRoles
(
    USUARIO_ID bigint NOT NULL,
    ROL_ID bigint NOT NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_UsuariosRoles_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_UsuariosRoles_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT PK_UsuariosRoles PRIMARY KEY(USUARIO_ID, ROL_ID),
    CONSTRAINT FK_UsuariosRoles_Usuarios FOREIGN KEY(USUARIO_ID) REFERENCES [ADMINISTRACION_USUARIOS].Usuarios(ID),
    CONSTRAINT FK_UsuariosRoles_Roles FOREIGN KEY(ROL_ID) REFERENCES [ADMINISTRACION_USUARIOS].Roles(ID)
);

IF OBJECT_ID(N'[ADMINISTRACION_USUARIOS].RefreshTokens', N'U') IS NULL
CREATE TABLE [ADMINISTRACION_USUARIOS].RefreshTokens
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_RefreshTokens PRIMARY KEY,
    USUARIO_ID bigint NOT NULL,
    TOKEN_HASH varbinary(256) NOT NULL,
    EXPIRES_AT datetime2(7) NOT NULL,
    REVOKED_AT datetime2(7) NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_RefreshTokens_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_RefreshTokens_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_RefreshTokens_Usuarios FOREIGN KEY(USUARIO_ID) REFERENCES [ADMINISTRACION_USUARIOS].Usuarios(ID)
);

IF OBJECT_ID(N'[ADMINISTRACION_USUARIOS].LoginAttempts', N'U') IS NULL
CREATE TABLE [ADMINISTRACION_USUARIOS].LoginAttempts
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_LoginAttempts PRIMARY KEY,
    USUARIO_ID bigint NULL,
    NOMBRE_USUARIO nvarchar(100) NULL,
    EXITOSO bit NOT NULL,
    FECHA_INTENTO datetime2(7) NOT NULL CONSTRAINT DF_LoginAttempts_FECHA_INTENTO DEFAULT(SYSUTCDATETIME()),
    IP_ORIGEN nvarchar(45) NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_LoginAttempts_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_LoginAttempts_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_LoginAttempts_Usuarios FOREIGN KEY(USUARIO_ID) REFERENCES [ADMINISTRACION_USUARIOS].Usuarios(ID)
);

IF OBJECT_ID(N'[INVENTARIO].Productos', N'U') IS NULL
CREATE TABLE [INVENTARIO].Productos
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_Productos PRIMARY KEY,
    TIPO_PRODUCTO nvarchar(30) NOT NULL CONSTRAINT CK_Productos_TIPO_PRODUCTO CHECK(TIPO_PRODUCTO IN(N'Montura',N'Lente',N'Servicio')),
    SKU nvarchar(100) NOT NULL,
    NOMBRE nvarchar(200) NOT NULL,
    COSTO_UNITARIO decimal(18,2) NOT NULL CONSTRAINT CK_Productos_COSTO_UNITARIO CHECK(COSTO_UNITARIO >= 0),
    PRECIO_VENTA decimal(18,2) NOT NULL CONSTRAINT CK_Productos_PRECIO_VENTA CHECK(PRECIO_VENTA >= 0),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_Productos_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_Productos_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT UQ_Productos_SKU UNIQUE(SKU)
);

IF OBJECT_ID(N'[INVENTARIO].Monturas', N'U') IS NULL
CREATE TABLE [INVENTARIO].Monturas
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_Monturas PRIMARY KEY,
    ProductoID bigint NOT NULL,
    Marca nvarchar(100) NOT NULL,
    MODELO nvarchar(100) NOT NULL,
    MATERIAL nvarchar(100) NULL,
    COLOR nvarchar(100) NULL,
    TAMANIO nvarchar(50) NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_Monturas_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_Monturas_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_Monturas_Productos FOREIGN KEY(ProductoID) REFERENCES [INVENTARIO].Productos(ID)
);

IF OBJECT_ID(N'[INVENTARIO].Lentes', N'U') IS NULL
CREATE TABLE [INVENTARIO].Lentes
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_Lentes PRIMARY KEY,
    ProductoID bigint NOT NULL,
    Marca nvarchar(100) NOT NULL,
    FiltroID bigint NOT NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_Lentes_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_Lentes_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_Lentes_Productos FOREIGN KEY(ProductoID) REFERENCES [INVENTARIO].Productos(ID),
    CONSTRAINT FK_Lentes_FiltrosLente FOREIGN KEY(FiltroID) REFERENCES [CATALOGOS].FiltrosLente(ID)
);

IF OBJECT_ID(N'[INVENTARIO].LenteCOMPLEMENTOs', N'U') IS NULL
CREATE TABLE [INVENTARIO].LenteCOMPLEMENTOs
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_LenteCOMPLEMENTOs PRIMARY KEY,
    LenteID bigint NOT NULL,
    COMPLEMENTO nvarchar(100) NOT NULL,
    VALOR nvarchar(200) NULL,
    ACTIVO bit NOT NULL CONSTRAINT DF_LenteCOMPLEMENTOs_ACTIVO DEFAULT(1),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_LenteCOMPLEMENTOs_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_LenteCOMPLEMENTOs_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_LenteCOMPLEMENTOs_Lentes FOREIGN KEY(LenteID) REFERENCES [INVENTARIO].Lentes(ID)
);

IF OBJECT_ID(N'[INVENTARIO].LenteParticiones', N'U') IS NULL
CREATE TABLE [INVENTARIO].LenteParticiones
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_LenteParticiones PRIMARY KEY,
    LenteID bigint NOT NULL,
    CODIGO_PARTICION nvarchar(100) NOT NULL,
    Descripcion nvarchar(200) NULL,
    ACTIVO bit NOT NULL CONSTRAINT DF_LenteParticiones_ACTIVO DEFAULT(1),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_LenteParticiones_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_LenteParticiones_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_LenteParticiones_Lentes FOREIGN KEY(LenteID) REFERENCES [INVENTARIO].Lentes(ID)
);

IF OBJECT_ID(N'[INVENTARIO].ProductosStock', N'U') IS NULL
CREATE TABLE [INVENTARIO].ProductosStock
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_ProductosStock PRIMARY KEY,
    ProductoID bigint NOT NULL,
    STOCK_ACTUAL int NOT NULL CONSTRAINT CK_ProductosStock_STOCK_ACTUAL CHECK(STOCK_ACTUAL >= 0),
    STOCK_MINIMO int NOT NULL CONSTRAINT CK_ProductosStock_STOCK_MINIMO CHECK(STOCK_MINIMO >= 0),
    ESTADO_PRODUCTO nvarchar(50) NOT NULL CONSTRAINT CK_ProductosStock_ESTADO_PRODUCTO CHECK(ESTADO_PRODUCTO IN(N'Disponible',N'EnElaboracion',N'PendienteEntrega',N'Entregado',N'Devuelto',N'Anulado')),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_ProductosStock_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_ProductosStock_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_ProductosStock_Productos FOREIGN KEY(ProductoID) REFERENCES [INVENTARIO].Productos(ID),
    CONSTRAINT UQ_ProductosStock_Producto UNIQUE(ProductoID)
);

IF OBJECT_ID(N'[INVENTARIO].KardexMovimientos', N'U') IS NULL
CREATE TABLE [INVENTARIO].KardexMovimientos
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_KardexMovimientos PRIMARY KEY,
    ProductoID bigint NOT NULL,
    FECHA_TRANSACCION datetime2(7) NOT NULL,
    Concepto nvarchar(200) NOT NULL,
    NUMERO_COMPROBANTE nvarchar(100) NULL,
    CANTIDAD int NOT NULL,
    COSTO_UNITARIO decimal(18,2) NOT NULL,
    COSTO_TOTAL decimal(18,2) NOT NULL,
    OrdenVentaID bigint NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_KardexMovimientos_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_KardexMovimientos_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_KardexMovimientos_Productos FOREIGN KEY(ProductoID) REFERENCES [INVENTARIO].Productos(ID)
);

IF OBJECT_ID(N'[CLIENTES].Clientes', N'U') IS NULL
CREATE TABLE [CLIENTES].Clientes
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_Clientes PRIMARY KEY,
    TipoIDentificacionID bigint NOT NULL,
    NumeroIDentificacion nvarchar(50) NOT NULL,
    NOMBRE nvarchar(200) NOT NULL,
    TELEFONO nvarchar(30) NOT NULL,
    Email nvarchar(200) NULL,
    DIRECCION nvarchar(300) NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_Clientes_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_Clientes_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_Clientes_TiposIDentificacion FOREIGN KEY(TipoIDentificacionID) REFERENCES [CATALOGOS].TiposIDentificacion(ID),
    CONSTRAINT UQ_Clientes_NumeroIDentificacion UNIQUE(NumeroIDentificacion)
);

IF OBJECT_ID(N'[CLINICA].FormulasOptometricas', N'U') IS NULL
CREATE TABLE [CLINICA].FormulasOptometricas
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_FormulasOptometricas PRIMARY KEY,
    ClienteID bigint NOT NULL,
    FECHA_REGISTRO datetime2(7) NOT NULL CONSTRAINT DF_FormulasOptometricas_FECHA_REGISTRO DEFAULT(SYSUTCDATETIME()),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_FormulasOptometricas_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_FormulasOptometricas_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_FormulasOptometricas_Clientes FOREIGN KEY(ClienteID) REFERENCES [CLIENTES].Clientes(ID)
);

IF OBJECT_ID(N'[CLINICA].FormulaOJOs', N'U') IS NULL
CREATE TABLE [CLINICA].FormulaOJOs
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_FormulaOJOs PRIMARY KEY,
    FormulaID bigint NOT NULL,
    OJO nvarchar(2) NOT NULL CONSTRAINT CK_FormulaOJOs_OJO CHECK(OJO IN(N'OD',N'OI')),
    ESFERA decimal(6,2) NOT NULL,
    DISTANCIA_PUPILAR decimal(5,2) NOT NULL CONSTRAINT CK_FormulaOJOs_DP CHECK(DISTANCIA_PUPILAR > 0),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_FormulaOJOs_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_FormulaOJOs_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_FormulaOJOs_Formulas FOREIGN KEY(FormulaID) REFERENCES [CLINICA].FormulasOptometricas(ID)
);

IF OBJECT_ID(N'[CLINICA].FormulaCamposCondicionales', N'U') IS NULL
CREATE TABLE [CLINICA].FormulaCamposCondicionales
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_FormulaCamposCondicionales PRIMARY KEY,
    FormulaOJOID bigint NOT NULL,
    TIENE_CILINDRO bit NOT NULL CONSTRAINT DF_FormulaCamposCondicionales_TIENE_CILINDRO DEFAULT(0),
    CILINDRO decimal(6,2) NULL,
    EJE int NULL CONSTRAINT CK_FormulaCamposCondicionales_EJE CHECK(EJE IS NULL OR (EJE BETWEEN 0 AND 180)),
    TIENE_ADICION bit NOT NULL CONSTRAINT DF_FormulaCamposCondicionales_TIENE_ADICION DEFAULT(0),
    ADICION decimal(6,2) NULL,
    TIENE_PRISMA bit NOT NULL CONSTRAINT DF_FormulaCamposCondicionales_TIENE_PRISMA DEFAULT(0),
    PRISMA decimal(6,2) NULL,
    BASE nvarchar(20) NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_FormulaCamposCondicionales_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_FormulaCamposCondicionales_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_FormulaCamposCondicionales_FormulaOJOs FOREIGN KEY(FormulaOJOID) REFERENCES [CLINICA].FormulaOJOs(ID)
);

IF OBJECT_ID(N'[CLINICA].RECOMENDACIONesOptometra', N'U') IS NULL
CREATE TABLE [CLINICA].RECOMENDACIONesOptometra
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_RECOMENDACIONesOptometra PRIMARY KEY,
    FormulaID bigint NOT NULL,
    OptometraUSUARIO_ID bigint NOT NULL,
    RECOMENDACION nvarchar(max) NOT NULL,
    FechaRECOMENDACION datetime2(7) NOT NULL CONSTRAINT DF_RECOMENDACIONesOptometra_FechaRECOMENDACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_RECOMENDACIONesOptometra_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_RECOMENDACIONesOptometra_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_RECOMENDACIONesOptometra_Formulas FOREIGN KEY(FormulaID) REFERENCES [CLINICA].FormulasOptometricas(ID),
    CONSTRAINT FK_RECOMENDACIONesOptometra_Usuarios FOREIGN KEY(OptometraUSUARIO_ID) REFERENCES [ADMINISTRACION_USUARIOS].Usuarios(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].OrdenesVenta', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].OrdenesVenta
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_OrdenesVenta PRIMARY KEY,
    ClienteID bigint NOT NULL,
    EstadoOrdenID bigint NOT NULL,
    FECHA_APERTURA datetime2(7) NOT NULL CONSTRAINT DF_OrdenesVenta_FECHA_APERTURA DEFAULT(SYSUTCDATETIME()),
    FECHA_PRIMER_ABONO datetime2(7) NULL,
    FECHA_PAGO_TOTAL datetime2(7) NULL,
    FECHA_ENTREGA datetime2(7) NULL,
    TOTAL decimal(18,2) NOT NULL CONSTRAINT CK_OrdenesVenta_TOTAL CHECK(TOTAL >= 0),
    SALDO_PENDIENTE decimal(18,2) NOT NULL CONSTRAINT CK_OrdenesVenta_SALDO_PENDIENTE CHECK(SALDO_PENDIENTE >= 0),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_OrdenesVenta_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_OrdenesVenta_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_OrdenesVenta_Clientes FOREIGN KEY(ClienteID) REFERENCES [CLIENTES].Clientes(ID),
    CONSTRAINT FK_OrdenesVenta_EstadosOrden FOREIGN KEY(EstadoOrdenID) REFERENCES [CATALOGOS].EstadosOrden(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].OrdenesVentaDetalle', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].OrdenesVentaDetalle
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_OrdenesVentaDetalle PRIMARY KEY,
    OrdenVentaID bigint NOT NULL,
    ProductoID bigint NOT NULL,
    CANTIDAD int NOT NULL CONSTRAINT CK_OrdenesVentaDetalle_CANTIDAD CHECK(CANTIDAD > 0),
    PrecioUnitario decimal(18,2) NOT NULL CONSTRAINT CK_OrdenesVentaDetalle_Precio CHECK(PrecioUnitario >= 0),
    Subtotal decimal(18,2) NOT NULL CONSTRAINT CK_OrdenesVentaDetalle_Subtotal CHECK(Subtotal >= 0),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_OrdenesVentaDetalle_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_OrdenesVentaDetalle_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_OrdenesVentaDetalle_Ordenes FOREIGN KEY(OrdenVentaID) REFERENCES [COMERCIAL_VENTAS].OrdenesVenta(ID),
    CONSTRAINT FK_OrdenesVentaDetalle_Productos FOREIGN KEY(ProductoID) REFERENCES [INVENTARIO].Productos(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].OrdenesVentaFormula', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].OrdenesVentaFormula
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_OrdenesVentaFormula PRIMARY KEY,
    OrdenVentaID bigint NOT NULL,
    FormulaID bigint NOT NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_OrdenesVentaFormula_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_OrdenesVentaFormula_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_OrdenesVentaFormula_Ordenes FOREIGN KEY(OrdenVentaID) REFERENCES [COMERCIAL_VENTAS].OrdenesVenta(ID),
    CONSTRAINT FK_OrdenesVentaFormula_Formulas FOREIGN KEY(FormulaID) REFERENCES [CLINICA].FormulasOptometricas(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].Pagos', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].Pagos
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_Pagos PRIMARY KEY,
    OrdenVentaID bigint NOT NULL,
    MetodoPagoID bigint NOT NULL,
    MONTO decimal(18,2) NOT NULL CONSTRAINT CK_Pagos_MONTO CHECK(MONTO > 0),
    FECHA_PAGO datetime2(7) NOT NULL CONSTRAINT DF_Pagos_FECHA_PAGO DEFAULT(SYSUTCDATETIME()),
    NUMERO_COMPROBANTE nvarchar(100) NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_Pagos_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_Pagos_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_Pagos_Ordenes FOREIGN KEY(OrdenVentaID) REFERENCES [COMERCIAL_VENTAS].OrdenesVenta(ID),
    CONSTRAINT FK_Pagos_MetodosPago FOREIGN KEY(MetodoPagoID) REFERENCES [CATALOGOS].MetodosPago(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].TicketsVenta', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].TicketsVenta
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_TicketsVenta PRIMARY KEY,
    OrdenVentaID bigint NOT NULL,
    NUMERO_TICKET_INTERNO nvarchar(100) NOT NULL,
    FECHA_EMISION datetime2(7) NOT NULL CONSTRAINT DF_TicketsVenta_FECHA_EMISION DEFAULT(SYSUTCDATETIME()),
    DETALLE_JSON nvarchar(max) NOT NULL,
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_TicketsVenta_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_TicketsVenta_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_TicketsVenta_Ordenes FOREIGN KEY(OrdenVentaID) REFERENCES [COMERCIAL_VENTAS].OrdenesVenta(ID),
    CONSTRAINT UQ_TicketsVenta_NumeroTicket UNIQUE(NUMERO_TICKET_INTERNO)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].Devoluciones', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].Devoluciones
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_Devoluciones PRIMARY KEY,
    OrdenVentaID bigint NOT NULL,
    MOTIVO nvarchar(300) NOT NULL,
    FECHA_DEVOLUCION datetime2(7) NOT NULL CONSTRAINT DF_Devoluciones_FECHA_DEVOLUCION DEFAULT(SYSUTCDATETIME()),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_Devoluciones_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_Devoluciones_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_Devoluciones_Ordenes FOREIGN KEY(OrdenVentaID) REFERENCES [COMERCIAL_VENTAS].OrdenesVenta(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].DevolucionesDetalle', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].DevolucionesDetalle
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_DevolucionesDetalle PRIMARY KEY,
    DevolucionID bigint NOT NULL,
    OrdenVentaDetalleID bigint NOT NULL,
    CANTIDAD int NOT NULL CONSTRAINT CK_DevolucionesDetalle_CANTIDAD CHECK(CANTIDAD > 0),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_DevolucionesDetalle_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_DevolucionesDetalle_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_DevolucionesDetalle_Devoluciones FOREIGN KEY(DevolucionID) REFERENCES [COMERCIAL_VENTAS].Devoluciones(ID),
    CONSTRAINT FK_DevolucionesDetalle_OrdenDetalle FOREIGN KEY(OrdenVentaDetalleID) REFERENCES [COMERCIAL_VENTAS].OrdenesVentaDetalle(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].AnulacionesVenta', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].AnulacionesVenta
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_AnulacionesVenta PRIMARY KEY,
    OrdenVentaID bigint NOT NULL,
    MOTIVO nvarchar(300) NOT NULL,
    FechaAnulacion datetime2(7) NOT NULL CONSTRAINT DF_AnulacionesVenta_FechaAnulacion DEFAULT(SYSUTCDATETIME()),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_AnulacionesVenta_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_AnulacionesVenta_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_AnulacionesVenta_Ordenes FOREIGN KEY(OrdenVentaID) REFERENCES [COMERCIAL_VENTAS].OrdenesVenta(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].CambiosVenta', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].CambiosVenta
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_CambiosVenta PRIMARY KEY,
    OrdenVentaID bigint NOT NULL,
    MOTIVO nvarchar(300) NOT NULL,
    FECHA_CAMBIO datetime2(7) NOT NULL CONSTRAINT DF_CambiosVenta_FECHA_CAMBIO DEFAULT(SYSUTCDATETIME()),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_CambiosVenta_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_CambiosVenta_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_CambiosVenta_Ordenes FOREIGN KEY(OrdenVentaID) REFERENCES [COMERCIAL_VENTAS].OrdenesVenta(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].CambiosVentaDetalle', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].CambiosVentaDetalle
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_CambiosVentaDetalle PRIMARY KEY,
    CambioVentaID bigint NOT NULL,
    ProductoID bigint NOT NULL,
    CANTIDAD int NOT NULL CONSTRAINT CK_CambiosVentaDetalle_CANTIDAD CHECK(CANTIDAD > 0),
    TIPO_CAMBIO nvarchar(30) NOT NULL CONSTRAINT CK_CambiosVentaDetalle_TIPO_CAMBIO CHECK(TIPO_CAMBIO IN(N'Entrada',N'Salida')),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_CambiosVentaDetalle_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_CambiosVentaDetalle_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_CambiosVentaDetalle_Cambios FOREIGN KEY(CambioVentaID) REFERENCES [COMERCIAL_VENTAS].CambiosVenta(ID),
    CONSTRAINT FK_CambiosVentaDetalle_Productos FOREIGN KEY(ProductoID) REFERENCES [INVENTARIO].Productos(ID)
);

IF OBJECT_ID(N'[COMERCIAL_VENTAS].NotasCredito', N'U') IS NULL
CREATE TABLE [COMERCIAL_VENTAS].NotasCredito
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_NotasCredito PRIMARY KEY,
    OrdenVentaID bigint NOT NULL,
    MONTO decimal(18,2) NOT NULL CONSTRAINT CK_NotasCredito_MONTO CHECK(MONTO > 0),
    MOTIVO nvarchar(300) NOT NULL,
    FECHA_NOTA datetime2(7) NOT NULL CONSTRAINT DF_NotasCredito_FECHA_NOTA DEFAULT(SYSUTCDATETIME()),
    USUARIO_CREACION bigint NULL,
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_NotasCredito_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_NotasCredito_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_NotasCredito_Ordenes FOREIGN KEY(OrdenVentaID) REFERENCES [COMERCIAL_VENTAS].OrdenesVenta(ID)
);

IF OBJECT_ID(N'[NOTIFICACIONES].NotificacionesStock', N'U') IS NULL
CREATE TABLE [NOTIFICACIONES].NotificacionesStock
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_NotificacionesStock PRIMARY KEY,
    ProductoID bigint NOT NULL,
    MENSAJE nvarchar(300) NOT NULL,
    LEIDA bit NOT NULL CONSTRAINT DF_NotificacionesStock_LEIDA DEFAULT(0),
    FECHA_CREACION datetime2(7) NOT NULL CONSTRAINT DF_NotificacionesStock_FECHA_CREACION DEFAULT(SYSUTCDATETIME()),
    USUARIO_CREACION bigint NULL,
    USUARIO_ACTUALIZACION bigint NULL,
    FECHA_ACTUALIZACION datetime2(7) NOT NULL CONSTRAINT DF_NotificacionesStock_FECHA_ACTUALIZACION DEFAULT(SYSUTCDATETIME()),
    CONSTRAINT FK_NotificacionesStock_Productos FOREIGN KEY(ProductoID) REFERENCES [INVENTARIO].Productos(ID)
);

IF OBJECT_ID(N'[AUDITORIA].LogProductos', N'U') IS NULL
CREATE TABLE [AUDITORIA].LogProductos
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_LogProductos PRIMARY KEY,
    TABLA_ORIGEN nvarchar(128) NOT NULL,
    RegistroID bigint NOT NULL,
    ACCION nvarchar(30) NOT NULL,
    DATOS_ANTES nvarchar(max) NULL,
    DATOS_DESPUES nvarchar(max) NULL,
    USUARIO_ACCION bigint NULL,
    FECHA_ACCION datetime2(7) NOT NULL CONSTRAINT DF_LogProductos_FECHA_ACCION DEFAULT(SYSUTCDATETIME())
);

IF OBJECT_ID(N'[AUDITORIA].LogUsuarios', N'U') IS NULL
CREATE TABLE [AUDITORIA].LogUsuarios
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_LogUsuarios PRIMARY KEY,
    TABLA_ORIGEN nvarchar(128) NOT NULL,
    RegistroID bigint NOT NULL,
    ACCION nvarchar(30) NOT NULL,
    DATOS_ANTES nvarchar(max) NULL,
    DATOS_DESPUES nvarchar(max) NULL,
    USUARIO_ACCION bigint NULL,
    FECHA_ACCION datetime2(7) NOT NULL CONSTRAINT DF_LogUsuarios_FECHA_ACCION DEFAULT(SYSUTCDATETIME())
);

IF OBJECT_ID(N'[AUDITORIA].LogClientes', N'U') IS NULL
CREATE TABLE [AUDITORIA].LogClientes
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_LogClientes PRIMARY KEY,
    TABLA_ORIGEN nvarchar(128) NOT NULL,
    RegistroID bigint NOT NULL,
    ACCION nvarchar(30) NOT NULL,
    DATOS_ANTES nvarchar(max) NULL,
    DATOS_DESPUES nvarchar(max) NULL,
    USUARIO_ACCION bigint NULL,
    FECHA_ACCION datetime2(7) NOT NULL CONSTRAINT DF_LogClientes_FECHA_ACCION DEFAULT(SYSUTCDATETIME())
);

IF OBJECT_ID(N'[AUDITORIA].LogOrdenesVenta', N'U') IS NULL
CREATE TABLE [AUDITORIA].LogOrdenesVenta
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_LogOrdenesVenta PRIMARY KEY,
    TABLA_ORIGEN nvarchar(128) NOT NULL,
    RegistroID bigint NOT NULL,
    ACCION nvarchar(30) NOT NULL,
    DATOS_ANTES nvarchar(max) NULL,
    DATOS_DESPUES nvarchar(max) NULL,
    USUARIO_ACCION bigint NULL,
    FECHA_ACCION datetime2(7) NOT NULL CONSTRAINT DF_LogOrdenesVenta_FECHA_ACCION DEFAULT(SYSUTCDATETIME())
);

IF OBJECT_ID(N'[AUDITORIA].LogPagos', N'U') IS NULL
CREATE TABLE [AUDITORIA].LogPagos
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_LogPagos PRIMARY KEY,
    TABLA_ORIGEN nvarchar(128) NOT NULL,
    RegistroID bigint NOT NULL,
    ACCION nvarchar(30) NOT NULL,
    DATOS_ANTES nvarchar(max) NULL,
    DATOS_DESPUES nvarchar(max) NULL,
    USUARIO_ACCION bigint NULL,
    FECHA_ACCION datetime2(7) NOT NULL CONSTRAINT DF_LogPagos_FECHA_ACCION DEFAULT(SYSUTCDATETIME())
);

IF OBJECT_ID(N'[AUDITORIA].LogFormulasOptometricas', N'U') IS NULL
CREATE TABLE [AUDITORIA].LogFormulasOptometricas
(
    ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_LogFormulasOptometricas PRIMARY KEY,
    TABLA_ORIGEN nvarchar(128) NOT NULL,
    RegistroID bigint NOT NULL,
    ACCION nvarchar(30) NOT NULL,
    DATOS_ANTES nvarchar(max) NULL,
    DATOS_DESPUES nvarchar(max) NULL,
    USUARIO_ACCION bigint NULL,
    FECHA_ACCION datetime2(7) NOT NULL CONSTRAINT DF_LogFormulasOptometricas_FECHA_ACCION DEFAULT(SYSUTCDATETIME())
);

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_OrdenesVenta_ClienteEstado' AND object_id=OBJECT_ID(N'[COMERCIAL_VENTAS].OrdenesVenta'))
CREATE INDEX IX_OrdenesVenta_ClienteEstado ON [COMERCIAL_VENTAS].OrdenesVenta(ClienteID, EstadoOrdenID);

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Pagos_OrdenFecha' AND object_id=OBJECT_ID(N'[COMERCIAL_VENTAS].Pagos'))
CREATE INDEX IX_Pagos_OrdenFecha ON [COMERCIAL_VENTAS].Pagos(OrdenVentaID, FECHA_PAGO);

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Kardex_ProductoFecha' AND object_id=OBJECT_ID(N'[INVENTARIO].KardexMovimientos'))
CREATE INDEX IX_Kardex_ProductoFecha ON [INVENTARIO].KardexMovimientos(ProductoID, FECHA_TRANSACCION);

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Formulas_ClienteFecha' AND object_id=OBJECT_ID(N'[CLINICA].FormulasOptometricas'))
CREATE INDEX IX_Formulas_ClienteFecha ON [CLINICA].FormulasOptometricas(ClienteID, FECHA_REGISTRO);

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_ProductosStock_STOCK_MINIMO' AND object_id=OBJECT_ID(N'[INVENTARIO].ProductosStock'))
CREATE INDEX IX_ProductosStock_STOCK_MINIMO ON [INVENTARIO].ProductosStock(STOCK_ACTUAL, STOCK_MINIMO);

IF NOT EXISTS(SELECT 1 FROM [CATALOGOS].EstadosOrden)
BEGIN
    INSERT [CATALOGOS].EstadosOrden(CODIGO, NOMBRE) VALUES(N'Abierta',N'Abierta');
    INSERT [CATALOGOS].EstadosOrden(CODIGO, NOMBRE) VALUES(N'Abonada',N'Abonada');
    INSERT [CATALOGOS].EstadosOrden(CODIGO, NOMBRE) VALUES(N'Pagada',N'Pagada');
    INSERT [CATALOGOS].EstadosOrden(CODIGO, NOMBRE) VALUES(N'Entregada',N'Entregada');
    INSERT [CATALOGOS].EstadosOrden(CODIGO, NOMBRE) VALUES(N'Cancelada',N'Cancelada');
    INSERT [CATALOGOS].EstadosOrden(CODIGO, NOMBRE) VALUES(N'Anulada',N'Anulada');
END;

IF NOT EXISTS(SELECT 1 FROM [CATALOGOS].MetodosPago)
BEGIN
    INSERT [CATALOGOS].MetodosPago(CODIGO, NOMBRE) VALUES(N'Efectivo',N'Efectivo');
    INSERT [CATALOGOS].MetodosPago(CODIGO, NOMBRE) VALUES(N'Transferencia',N'Transferencia');
    INSERT [CATALOGOS].MetodosPago(CODIGO, NOMBRE) VALUES(N'Nequi',N'Nequi');
    INSERT [CATALOGOS].MetodosPago(CODIGO, NOMBRE) VALUES(N'Tarjeta',N'Tarjeta');
END;

IF NOT EXISTS(SELECT 1 FROM [CATALOGOS].FiltrosLente)
BEGIN
    INSERT [CATALOGOS].FiltrosLente(NOMBRE) VALUES(N'Blue');
    INSERT [CATALOGOS].FiltrosLente(NOMBRE) VALUES(N'Antireflejo');
    INSERT [CATALOGOS].FiltrosLente(NOMBRE) VALUES(N'Normal');
END;

IF NOT EXISTS(SELECT 1 FROM [ADMINISTRACION_USUARIOS].Roles)
BEGIN
    INSERT [ADMINISTRACION_USUARIOS].Roles(CODIGO, NOMBRE) VALUES(N'Administrador',N'Administrador');
    INSERT [ADMINISTRACION_USUARIOS].Roles(CODIGO, NOMBRE) VALUES(N'Vendedor',N'Vendedor');
    INSERT [ADMINISTRACION_USUARIOS].Roles(CODIGO, NOMBRE) VALUES(N'Optometra',N'Optómetra');
END;
